Changed Jenkinsfile to install pip3 and ansible if needed.

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -10,6 +10,32 @@ pipeline {
       }
     }
 
+    stage('Install pip3 (if needed)') {
+      steps {
+        sh '''
+          if ! command -v pip3 > /dev/null; then
+            echo "pip3 not found. Installing..."
+            sudo apt update && sudo apt install -y python3-pip
+          else
+            echo "pip3 is already installed."
+          fi
+        '''
+      }    
+    }
+
+    stage('Install ansible (if needed)') {
+      steps {
+        sh '''
+          if ! command -v ansible > /dev/null; then
+            echo "Ansible not found. Installing..."
+            sudo apt update && sudo apt install -y ansible
+          else
+            echo "Ansibleis already installed."
+          fi
+        '''
+      }
+    }
+
     stage('Install Requirements') {
       steps {
         sh 'pip3 install -r app/requirements.txt'
